all: src/main.cpp src/controlador.cpp src/cache.cpp src/motorPrefetch.cpp src/secPrefetch.cpp src/salPrefetch.cpp
	g++ src/main.cpp src/controlador.cpp src/cache.cpp src/motorPrefetch.cpp src/secPrefetch.cpp src/salPrefetch.cpp -o prefetch
clean:
	rm prefetch