all: src/main.cpp src/menu.cpp src/cache.cpp src/motorPrefetch.cpp src/secPrefetch.cpp src/salPrefetch.cpp
	g++ src/main.cpp src/menu.cpp src/cache.cpp src/motorPrefetch.cpp src/secPrefetch.cpp src/salPrefetch.cpp -o src/cachePrefetching
clean:
	rm src/cachePrefetching